os:
  - linux
dist: bionic
language: python

cache:
  directories:
    - eggs
    - downloads

python:
  - 2.7

env:
  - PLONE_VERSION=4
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2

install:
  - sed -ie "s#test-5.1#test-$PLONE_VERSION#" travis.cfg
  - virtualenv .
  - bin/pip install -r requirements.txt
  - mkdir -p buildout-cache/{eggs,downloads}
  - bin/buildout -c travis.cfg buildout:download-cache=downloads buildout:eggs-directory=eggs annotate
  - bin/buildout -c travis.cfg buildout:download-cache=downloads buildout:eggs-directory=eggs

script:
  - bin/test --test=\!"robot"

after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install -q coveralls
  - bin/coveralls

notifications:
  email:
    - devs@imio.be
